TOKEN = ""
PREFIX = "f!"

MIN_WORK = 5
MAX_WORK = 200
WORK_COMMAND = "work"
WORK_MIN_COOLDOWN_ = 30
WORK_MAX_COOLDOWN = 60

MIN_CRIME = 100
MAX_CRIME = 1500
CRIME_FAIL_CHANCE = 60
CRIME_COMMAND = "crime"
CRIME_MIN_COOLDOWN_ = 450
CRIME_MAX_COOLDOWN = 900

ROB_COMMAND = "rob"
ROB_FAIL_CHANCE = 80

LEADERBOARD_ROLE = "KJ"
LEADERBOARD_COMMAND = "lb"

MIN_BET_BLACKJACK = 1
MAX_BET_BLACKJACK = 99999999
STARTING_CARDS = 2

MEME_COMMAND = "meme"

MIN_BET_RPS = 1
MAX_BET_RPS = 99999999
SCISSORS = "scissors"
ROCK = "rock"
PAPER = "paper"
RPS_FAIL_CHANCE = 50 # I add this cuz i want to trick people and make them spend more money :3